coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 75%
        threshold: 10%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
